-- На всякий случай удалим таблицы, если уже есть
DROP TABLE IF EXISTS TEACHER       CASCADE;
DROP TABLE IF EXISTS SUBJECT       CASCADE;
DROP TABLE IF EXISTS PULPIT        CASCADE;
DROP TABLE IF EXISTS AUDITORIUM    CASCADE;
DROP TABLE IF EXISTS AUDITORIUM_TYPE CASCADE;
DROP TABLE IF EXISTS FACULTY       CASCADE;

-- 1. FACULTY
CREATE TABLE FACULTY (
    FACULTY       CHAR(10) PRIMARY KEY,
    FACULTY_NAME  VARCHAR(100) NOT NULL
);

-- 2. PULPIT (кафедра) — ссылается на FACULTY
CREATE TABLE PULPIT (
    PULPIT        CHAR(10) PRIMARY KEY,
    PULPIT_NAME   VARCHAR(100) NOT NULL,
    FACULTY       CHAR(10) NOT NULL,
    CONSTRAINT fk_pulpit_faculty
        FOREIGN KEY (FACULTY)
        REFERENCES FACULTY(FACULTY)
);

-- 3. TEACHER — ссылается на PULPIT
CREATE TABLE TEACHER (
    TEACHER       CHAR(10) PRIMARY KEY,
    TEACHER_NAME  VARCHAR(100) NOT NULL,
    PULPIT        CHAR(10) NOT NULL,
    CONSTRAINT fk_teacher_pulpit
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
);

-- 4. SUBJECT — ссылается на PULPIT
CREATE TABLE SUBJECT (
    SUBJECT       CHAR(10) PRIMARY KEY,
    SUBJECT_NAME  VARCHAR(100) NOT NULL,
    PULPIT        CHAR(10) NOT NULL,
    CONSTRAINT fk_subject_pulpit
        FOREIGN KEY (PULPIT)
        REFERENCES PULPIT(PULPIT)
);

-- 5. AUDITORIUM_TYPE
CREATE TABLE AUDITORIUM_TYPE (
    AUDITORIUM_TYPE      CHAR(10) PRIMARY KEY,
    AUDITORIUM_TYPENAME  VARCHAR(100) NOT NULL
);

-- 6. AUDITORIUM — ссылается на AUDITORIUM_TYPE
CREATE TABLE AUDITORIUM (
    AUDITORIUM        CHAR(10) PRIMARY KEY,
    AUDITORIUM_NAME   VARCHAR(100) NOT NULL,
    AUDITORIUM_CAPACITY INTEGER NOT NULL,
    AUDITORIUM_TYPE   CHAR(10) NOT NULL,
    CONSTRAINT fk_auditorium_type
        FOREIGN KEY (AUDITORIUM_TYPE)
        REFERENCES AUDITORIUM_TYPE(AUDITORIUM_TYPE)
);


-- FACULTY
INSERT INTO FACULTY (FACULTY, FACULTY_NAME) VALUES
('F001', 'Факультет математики'),
('F002', 'Факультет информатики');

-- PULPIT  (faculty_id: 1 → F001, 2 → F002)
INSERT INTO PULPIT (PULPIT, PULPIT_NAME, FACULTY) VALUES 
('P001', 'Кафедра информатики',          'F002'),
('P002', 'Кафедра высшей математики',    'F001'),
('P003', 'Кафедра компьютерных наук',    'F002');

-- TEACHER (привяжем преподавателей к кафедрам P001 и P002)
INSERT INTO TEACHER (TEACHER, TEACHER_NAME, PULPIT) VALUES
('T001', 'Иванов Иван Иванович',   'P001'),
('T002', 'Петрова Анна Сергеевна', 'P002');

-- AUDITORIUM_TYPE
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES
('AT01', 'Лекционный'),
('AT02', 'Практический');

-- AUDITORIUM (auditorium_type_id: 1 → AT01, 2 → AT02)
INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE) VALUES
('A101', 'Аудитория 101', 30, 'AT01'),
('A102', 'Аудитория 102', 50, 'AT02');

-- SUBJECT (pulpit_id: 1 → P001, 2 → P002)
INSERT INTO SUBJECT (SUBJECT, SUBJECT_NAME, PULPIT) VALUES
('S001', 'Математический анализ', 'P001'),
('S002', 'Программирование',      'P002');

SELECT * FROM Pulpit;
SELECT * FROM Auditorium;
SELECT * FROM Faculty;
SELECT * FROM Subject;
SELECT * FROM Teacher;


CREATE ROLE univer_admin
    WITH LOGIN
    PASSWORD '1111'
    SUPERUSER
    CREATEDB
    CREATEROLE;