
//1

select * from dba_pdbs;


//2

select * from v$instance;


//3

SELECT comp_id, comp_name, version, status FROM dba_registry;


//4

//docker exec -it oracle-free-official dbca -silent -createPluggableDatabase
//-pdbName BVV_PDB -sourceDB FREE -createPDBFrom DEFAULT -fileNameConvert /opt/oracle/product/23ai/BVV_PDB

/////////////////////////////////////////////////////////
//5

SELECT PDB_NAME FROM DBA_PDBS;

//6
ALTER SESSION SET CONTAINER = BVV_PDB;
//ALTER SESSION SET CONTAINER = CDB$ROOT;


//BVV_PDBConntect
ALTER PLUGGABLE DATABASE BVV_PDB OPEN;

CREATE TABLESPACE TS_PDB_BVV
    DATAFILE 'TS_PDB_BVV.dbf'
    SIZE 7M
    AUTOEXTEND ON NEXT 5M
    EXTENT MANAGEMENT LOCAL;
    
    drop tablespace TS_PDB_BVV  INCLUDING CONTENTS AND DATAFILES;

    
CREATE TEMPORARY TABLESPACE TS_PDB_BVV_TEMP
    TEMPFILE 'TS_PDB_BVV_TEMP.dbf'
    SIZE 5M
    AUTOEXTEND ON NEXT 3M;
    
    drop tablespace TS_PDB_BVV_TEMP INCLUDING CONTENTS AND DATAFILES;

CREATE ROLE RL_PDB_BVVCORE;

DROP ROLE RL_PDB_BVVCORE;

GRANT CONNECT,
CREATE SESSION,
CREATE ANY TABLE, 
DROP ANY TABLE,
CREATE ANY VIEW, 
DROP ANY VIEW,
CREATE ANY PROCEDURE, 
DROP ANY PROCEDURE TO RL_PDB_BVVCORE;


CREATE PROFILE PF_PDB_BVVCORE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 5
    FAILED_LOGIN_ATTEMPTS 10
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP PROFILE PF_PDB_BVVCORE

CREATE USER U1_BVV_PDB IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_PDB_BVV QUOTA UNLIMITED ON TS_PDB_BVV
TEMPORARY TABLESPACE TS_PDB_BVV_TEMP
PROFILE PF_PDB_BVVCORE
ACCOUNT UNLOCK;

GRANT RL_PDB_BVVCORE TO U1_BVV_PDB;

//сессия BVV
DROP USER U1_BVV_PDB 

////////////////////////////////////////
//U1_BVV_PDB
//7

CREATE TABLE BVV_TABLE(a NUMBER, b VARCHAR2(10));


INSERT INTO BVV_TABLE VALUES(1, 'chebyrek');
INSERT INTO BVV_TABLE VALUES(2, 'lol');
COMMIT;

SELECT * FROM BVV_TABLE;

Drop Table BVV_TABLE;



//8
//BVV_PDBConnect
SELECT * FROM DBA_TABLESPACES;
SELECT ROLE FROM DBA_ROLES;
SELECT PROFILE FROM DBA_PROFILES;
SELECT USERNAME FROM DBA_USERS;

SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_DATA_FILES;
SELECT FILE_NAME, TABLESPACE_NAME FROM DBA_TEMP_FILES;
SELECT GRANTEE, PRIVILEGE FROM DBA_SYS_PRIVS;
SELECT grantee, granted_role FROM dba_role_privs where grantee = 'U1_BVV_PDB';


//9
//BVV_PDBConnect

ALTER SESSION SET CONTAINER = CDB$ROOT;

create user C##BVV identified by 123;
GRANT CONNECT, CREATE SESSION TO C##BVV;

ALTER SESSION SET CONTAINER = BVV_PDB;

GRANT CONNECT, CREATE SESSION TO C##BVV;

DROP USER C##BVV;


//10
//BVV_PDBConnect
alter pluggable database BVV_PDB close;
drop pluggable database BVV_PDB including datafiles;
select file_name from dba_data_files where tablespace_name = 'TS_BVV_PDB';
drop user C##BVV cascade;